### ISSUE TITLE
Settings.xml pointing to wrong DTD path

### ISSUE THREAD

**Issue by jonasraoni** [pkp/acron#3]
The settings.xml is pointing to the wrong DTD and fails to be validated.

**PRs**
- https://github.com/pkp/acron/pull/4
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3682

**Comment by jonasraoni** [comment]
@asmecher here I just fixed the DTD path and did minor updates on the way.
 **PRs**
- https://github.com/pkp/acron/pull/4
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3682

**Comment by asmecher** [comment]
Merged, thanks!
