### ISSUE TITLE
AcronPlugin::parseCronTab doesn't work with closures

### ISSUE THREAD

**Issue by jonasraoni** [pkp/acron#6]
An error happens when adding a closure to the list of hook callbacks:

```php
Hook::add('AcronPlugin::parseCronTab', $this->setupAcronTask(...));
```

**PRs**
- `main`
- https://github.com/pkp/acron/pull/8
- `stable-3_4_0`
- https://github.com/pkp/acron/pull/7

**Comment by jonasraoni** [comment]
@asmecher Just a minor bugfix, see PRs on the description.

**Comment by asmecher** [comment]
Both merged, thanks!
